name = "My Awesome Modpack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2e1962975265f3e6187ce344b6c0c6519d65b7d5f63bdd083790bba589ce7d9"

[versions]
forge = "47.4.12"
minecraft = "1.20.1"
